//! The checked-in documentation site under `docs/` is what `aipl docs` produces
//! from this repository's AIPL right now.
//!
//! Generated and committed for the same reason `editors/vscode/syntaxes/
//! aipl.tmLanguage.json` is: a reader (and a reviewer) can see the rendered
//! result without running anything, and a change that alters it shows up in the
//! diff where it can be judged. The cost is that it goes stale, which is what
//! [`checked_in_docs_are_current`] exists to catch — and what
//! `cargo handoff` regenerates rather than stopping on, since a `.doc("..")`
//! edit makes it stale every time.

use std::path::{Path, PathBuf};
use std::process::Command;

/// The exact invocation the checked-in site is generated by. The test and the
/// filler share it so they cannot drift, and it is the command a person would
/// run by hand.
const PATHS: &[&str] = &["crates", "examples"];
const NAME: &str = "AIPL";

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn checked_in() -> PathBuf {
    root().join("docs")
}

/// Run `aipl docs` into `out`. Shelling out rather than calling the library
/// keeps this honest about the whole path a user takes — argument handling, the
/// directory walk and the writer included.
fn generate(out: &Path) {
    let output = Command::new(env!("CARGO_BIN_EXE_aipl"))
        .current_dir(root())
        .arg("docs")
        .args(PATHS)
        .arg("-o")
        .arg(out)
        .arg("--name")
        .arg(NAME)
        .output()
        .expect("spawn aipl docs");
    assert!(
        output.status.success(),
        "`aipl docs` failed:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// Every file in `dir`, by name, with its contents.
fn read_dir(dir: &Path) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .flatten()
        .filter(|e| e.path().is_file())
        .map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            let body = std::fs::read_to_string(e.path())
                .unwrap_or_else(|err| panic!("{}: {err}", e.path().display()));
            (name, body)
        })
        .collect();
    out.sort();
    out
}

const REGENERATE: &str = "cargo test --test compiler -- --ignored docs_site::fill_docs";

#[test]
fn checked_in_docs_are_current() {
    let tmp = std::env::temp_dir().join(format!("aipl-docs-check-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&tmp);
    generate(&tmp);
    let fresh = read_dir(&tmp);
    let committed = read_dir(&checked_in());
    let _ = std::fs::remove_dir_all(&tmp);

    // Report the *set* of pages first: a file added or removed is a different
    // failure from a file whose contents moved, and saying which saves a diff.
    let fresh_names: Vec<&str> = fresh.iter().map(|(n, _)| n.as_str()).collect();
    let committed_names: Vec<&str> = committed.iter().map(|(n, _)| n.as_str()).collect();
    assert_eq!(
        fresh_names, committed_names,
        "docs/ has a different set of pages than `aipl docs` now produces. \
         Regenerate with:\n    {REGENERATE}"
    );

    for ((name, fresh), (_, committed)) in fresh.iter().zip(&committed) {
        assert_eq!(
            fresh, committed,
            "docs/{name} is out of date with the source it documents. Regenerate with:\n    \
             {REGENERATE}"
        );
    }
}

/// Author helper: rewrite `docs/` from the current source, then fail so the diff
/// gets reviewed before it is committed — the same shape as the other `fill_*`
/// helpers. `cargo handoff` runs this for you when the check above fails.
#[test]
#[ignore]
fn fill_docs() {
    let out = checked_in();
    // Remove first: a page for a deleted source file would otherwise be left
    // behind, and the currency check compares the whole directory.
    let _ = std::fs::remove_dir_all(&out);
    generate(&out);
    panic!("rewrote {} — review the diff", out.display());
}
