//! Compile the checked-in dogfood CLIF artifacts into machine code **at build
//! time**, so a normal `aipl` run never re-does that work.
//!
//! The compiler dogfoods AIPL: parsing (and formatting) call into AIPL
//! functions through the FFI, and those functions live as checked-in Cranelift
//! IR in `src/dogfood.clif` and `src/fmt.clif`. Linking them at process start
//! meant every invocation re-parsed several megabytes of IR and re-lowered ~470
//! functions to identical machine code — around 200ms before `aipl check` could
//! look at its first byte of input, paid again by every one of the hundreds of
//! subprocesses a test run spawns.
//!
//! So we do it once, here, into an object file linked into the binary. The
//! declaration order that makes an artifact link is subtle and shared with the
//! run-time path, so it lives in `aipl-artifact` and both callers use it; all
//! that differs is the module type and the fact that entry points need real
//! exported symbols here.
//!
//! Three things come out of this, into `OUT_DIR`:
//!
//! * `libaipl_prebuilt.a` — one object per artifact, archived and linked in.
//! * `prebuilt.rs` — the generated `extern` declarations and name→address
//!   tables, `include!`d by `lib.rs`.
//! * `<artifact>.manifest` — the artifact's `;`-comment header alone, which the
//!   runtime still needs for FFI signatures and struct layouts. Carrying just
//!   the header keeps the multi-megabyte IR bodies out of the binary.
//!
//! The JIT path stays exactly where it was, and is what `AIPL_DOGFOOD_IR` /
//! `AIPL_FMT_IR` select — so the staged-IR workflow can still validate
//! candidate IR across the corpus without a rebuild.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use cranelift::codegen::settings::{self, Configurable};
use cranelift_object::{ObjectBuilder, ObjectModule};

/// The artifacts to prebuild: the `.clif` under `src/`, and the prefix its
/// exported entry symbols get (they share a namespace once archived together).
const ARTIFACTS: &[(&str, &str)] = &[
    ("dogfood", "__aipl_pre_dogfood__"),
    ("fmt", "__aipl_pre_fmt__"),
];

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR")).join("src");

    // Cranelift lowers for the machine it is told about, and the checked-in IR
    // already names host calling conventions (`apple_aarch64`, …) in its
    // signatures — so this only makes sense building for the host. Cross-compiling
    // would need the artifacts regenerated for the target anyway; say so plainly
    // rather than emitting an object full of wrong-ABI calls.
    let host = std::env::var("HOST").expect("HOST");
    let target = std::env::var("TARGET").expect("TARGET");
    assert_eq!(
        host, target,
        "the prebuilt dogfood object is lowered for the host; cross-compiling to \
         {target} needs the checked-in .clif regenerated on that target"
    );

    let mut objects = Vec::new();
    // Which artifact each object was built from, so a test can catch a prebuilt
    // object that has drifted from the checked-in `.clif`.
    let mut fingerprints = String::new();
    let mut generated = String::from(
        "// @generated by build.rs — the prebuilt dogfood entry points.\n\
         // Each artifact's `; entry` functions, exported from the archived object\n\
         // under a per-artifact prefix, paired with the FFI name callers use.\n",
    );

    for (name, prefix) in ARTIFACTS {
        let clif = src_dir.join(format!("{name}.clif"));
        println!("cargo:rerun-if-changed={}", clif.display());
        let text = std::fs::read_to_string(&clif)
            .unwrap_or_else(|e| panic!("read {}: {e}", clif.display()));

        let manifest = aipl_artifact::parse_manifest(&text)
            .unwrap_or_else(|e| panic!("{name}.clif manifest: {e}"));

        // The runtime reads FFI signatures and struct layouts back out of the
        // header, so hand it the header and nothing else.
        std::fs::write(
            out_dir.join(format!("{name}.manifest")),
            manifest_header(&text),
        )
        .unwrap_or_else(|e| panic!("write {name}.manifest: {e}"));

        let exports: HashMap<u32, String> = manifest
            .entries
            .iter()
            .map(|e| (e.id, format!("{prefix}{}", e.name)))
            .collect();

        let mut module = object_module(name);
        aipl_artifact::link_artifact(
            &text,
            &manifest,
            &mut module,
            &aipl_artifact::LinkNames {
                // Local, so the several hundred non-entry functions neither
                // collide between the two artifacts nor show up in the binary's
                // symbol table.
                local_prefix: "__aipl_pre_fn",
                exports,
            },
        )
        .unwrap_or_else(|e| panic!("link {name}.clif: {e}"));

        let bytes = module
            .finish()
            .emit()
            .unwrap_or_else(|e| panic!("emit {name} object: {e}"));
        let obj = out_dir.join(format!("aipl_pre_{name}.o"));
        std::fs::write(&obj, bytes).unwrap_or_else(|e| panic!("write {}: {e}", obj.display()));
        objects.push(obj);

        generated.push_str("extern \"C\" {\n");
        for e in &manifest.entries {
            generated.push_str(&format!("    fn {prefix}{}();\n", e.name));
        }
        generated.push_str("}\n");
        generated.push_str(&format!(
            "static {}_PREBUILT: &[(&str, PrebuiltFn)] = &[\n",
            name.to_uppercase()
        ));
        for e in &manifest.entries {
            generated.push_str(&format!(
                "    ({:?}, {prefix}{} as PrebuiltFn),\n",
                e.name, e.name
            ));
        }
        generated.push_str("];\n");
        fingerprints.push_str(&format!(
            "    ({:?}, {}u64),\n",
            format!("{name}.clif"),
            aipl_artifact::fingerprint(&text)
        ));
    }
    generated.push_str(&format!(
        "static PREBUILT_FINGERPRINTS: &[(&str, u64)] = &[\n{fingerprints}];\n"
    ));

    std::fs::write(out_dir.join("prebuilt.rs"), generated).expect("write prebuilt.rs");

    // Archive the objects and link them in. An archive (rather than a bare
    // object) is what `cargo:rustc-link-lib` understands, and it propagates from
    // this library crate to whatever binary ends up containing it.
    let archive = out_dir.join("libaipl_prebuilt.a");
    let _ = std::fs::remove_file(&archive);
    archive_objects(&archive, &objects);
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=static=aipl_prebuilt");
    println!("cargo:rerun-if-changed=build.rs");
}

/// The artifact's leading `;`-comment block. Everything the manifest carries
/// precedes the CLIF bodies, which carry `;` comments of their own — so the
/// header is exactly the text up to the first `function ` line.
fn manifest_header(text: &str) -> String {
    let end = text
        .lines()
        .position(|l| l.trim_start().starts_with("function "))
        .unwrap_or_else(|| panic!("artifact has no `function` lines"));
    let mut out: String = text.lines().take(end).collect::<Vec<_>>().join("\n");
    out.push('\n');
    out
}

fn object_module(name: &str) -> ObjectModule {
    let mut flags = settings::builder();
    // Matches the JIT's `host_isa`, except for PIC: this object is linked into a
    // position-independent executable, so its calls into the runtime have to go
    // through the usual indirection rather than assume a fixed address.
    flags.set("use_colocated_libcalls", "false").expect("flag");
    flags.set("is_pic", "true").expect("flag");
    let isa = cranelift_native::builder()
        .unwrap_or_else(|msg| panic!("host machine not supported: {msg}"))
        .finish(settings::Flags::new(flags))
        .unwrap_or_else(|e| panic!("isa: {e}"));
    let builder = ObjectBuilder::new(
        isa,
        format!("aipl_pre_{name}"),
        cranelift_module::default_libcall_names(),
    )
    .unwrap_or_else(|e| panic!("object builder: {e}"));
    ObjectModule::new(builder)
}

/// Bundle the objects into a static archive with the toolchain's `ar`.
fn archive_objects(archive: &Path, objects: &[PathBuf]) {
    let ar = std::env::var("AR").unwrap_or_else(|_| "ar".into());
    let status = Command::new(&ar)
        .arg("crs")
        .arg(archive)
        .args(objects)
        .status()
        .unwrap_or_else(|e| panic!("invoke {ar}: {e}"));
    assert!(
        status.success(),
        "{ar} failed to build {}",
        archive.display()
    );
}
