//! Link the **checked-in compiled dogfood artifact** into this crate, so a
//! normal `aipl` run pays no Cranelift cost at all.
//!
//! The compiler dogfoods AIPL: parsing (and formatting) call into AIPL
//! functions through the FFI. Those functions are checked in already compiled —
//! `src/dogfood.o`, the native object, beside `src/dogfood.manifest`, the
//! `;`-comment header the runtime marshals against. This script archives the
//! object, links it in, and generates the `extern` declarations that reach it.
//!
//! **Why the object and not the IR.** Linking the IR at process start meant
//! every invocation re-parsed tens of megabytes and re-lowered ~470 functions to
//! identical machine code — ~200ms before `aipl check` saw its first byte, paid
//! again by every one of the hundreds of subprocesses a test run spawns. Lowering
//! it *here* fixed that but moved the cost onto every build that touched the
//! artifact (~20s of Cranelift, on top of an unavoidable relink). Checking in the
//! object removes it from both: nothing lowers the artifact except the command
//! that regenerates it (`dogfood_ir::promote_staged_ir`, via
//! `aipl_artifact::emit_object`), and the repository carries 7 MB of object
//! instead of 40 MB of text.
//!
//! The IR has not gone anywhere — it is still what the artifact is *generated*
//! as, and still what the staged-IR workflow validates through
//! `AIPL_DOGFOOD_IR` (`Compilation::from_artifact` JITs it). It is simply a
//! working-tree intermediate now rather than a checked-in file. The manifest's
//! `; source-fingerprint` line is what still ties the checked-in object to the
//! AIPL sources it came from; `checked_in_ir_is_current` regenerates the IR in
//! memory and compares against it.
//!
//! Two things come out of this, into `OUT_DIR`:
//!
//! * `libaipl_prebuilt.a` — the checked-in object, archived and linked in.
//! * `prebuilt.rs` — the generated `extern` declarations and name→address
//!   tables, `include!`d by `lib.rs`.

use std::path::{Path, PathBuf};
use std::process::Command;

use aipl_artifact::{ArtifactFiles, DOGFOOD};

/// The artifacts to link. One today; the loop below is written for the list so
/// a second costs an entry.
const ARTIFACTS: &[ArtifactFiles] = &[DOGFOOD];

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let src_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR")).join("src");

    // The checked-in object is lowered for the host, and the IR it came from
    // already names host calling conventions (`apple_aarch64`, …) in its
    // signatures — so this only makes sense building for the host.
    // Cross-compiling needs the artifact regenerated on that target anyway; say
    // so plainly rather than linking an object full of wrong-ABI calls.
    let host = std::env::var("HOST").expect("HOST");
    let target = std::env::var("TARGET").expect("TARGET");
    assert_eq!(
        host, target,
        "the checked-in dogfood object is lowered for the host; cross-compiling to \
         {target} needs the artifact regenerated on that target \
         (cargo test --test dogfood -- --ignored dogfood_ir::fill_dogfood_ir)"
    );

    let mut objects = Vec::new();
    // Which artifact each object was built from, so a test can catch a linked
    // object that has drifted from the AIPL sources.
    let mut fingerprints = String::new();
    let mut generated = String::from(
        "// @generated by build.rs — the prebuilt dogfood entry points.\n\
         // Each artifact's `; entry` functions, exported from the archived object\n\
         // under a per-artifact prefix, paired with the FFI name callers use.\n",
    );

    for a in ARTIFACTS {
        let object = src_dir.join(a.object);
        let manifest_path = src_dir.join(a.manifest);
        println!("cargo:rerun-if-changed={}", object.display());
        println!("cargo:rerun-if-changed={}", manifest_path.display());

        let manifest_text = std::fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
            panic!(
                "read {}: {e}\nRegenerate the artifact with: \
                 cargo test --test dogfood -- --ignored dogfood_ir::fill_dogfood_ir",
                manifest_path.display()
            )
        });
        let manifest = aipl_artifact::parse_manifest(&manifest_text)
            .unwrap_or_else(|e| panic!("{}: {e}", a.manifest));
        assert!(
            object.exists(),
            "missing {} — regenerate the artifact with: \
             cargo test --test dogfood -- --ignored dogfood_ir::fill_dogfood_ir",
            object.display()
        );

        // The runtime reads FFI signatures and struct layouts back out of the
        // header, and `lib.rs` `include_str!`s it from OUT_DIR.
        std::fs::write(out_dir.join(format!("{}.manifest", a.name)), &manifest_text)
            .unwrap_or_else(|e| panic!("write {}.manifest: {e}", a.name));
        objects.push(object);

        generated.push_str("extern \"C\" {\n");
        for e in &manifest.entries {
            generated.push_str(&format!("    fn {}{}();\n", a.prefix, e.name));
        }
        generated.push_str("}\n");
        generated.push_str(&format!(
            "static {}_PREBUILT: &[(&str, PrebuiltFn)] = &[\n",
            a.name.to_uppercase()
        ));
        for e in &manifest.entries {
            generated.push_str(&format!(
                "    ({:?}, {}{} as PrebuiltFn),\n",
                e.name, a.prefix, e.name
            ));
        }
        generated.push_str("];\n");
        let fp = aipl_artifact::source_fingerprint(&manifest_text).unwrap_or_else(|| {
            panic!(
                "{} carries no `{}` line — regenerate the artifact",
                a.manifest,
                aipl_artifact::SOURCE_FINGERPRINT_PREFIX.trim()
            )
        });
        fingerprints.push_str(&format!("    ({:?}, {fp}u64),\n", a.name));
    }
    generated.push_str(&format!(
        "static PREBUILT_FINGERPRINTS: &[(&str, u64)] = &[\n{fingerprints}];\n"
    ));

    std::fs::write(out_dir.join("prebuilt.rs"), generated).expect("write prebuilt.rs");

    // Archive the objects and link them in. An archive (rather than a bare
    // object) is what `cargo:rustc-link-lib` understands, and it propagates from
    // this library crate to whatever binary ends up containing it.
    let archive = out_dir.join("libaipl_prebuilt.a");
    let _ = std::fs::remove_file(&archive);
    archive_objects(&archive, &objects);
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=static=aipl_prebuilt");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Bundle the objects into a static archive with the toolchain's `ar`.
fn archive_objects(archive: &Path, objects: &[PathBuf]) {
    let ar = std::env::var("AR").unwrap_or_else(|_| "ar".into());
    let status = Command::new(&ar)
        .arg("crs")
        .arg(archive)
        .args(objects)
        .status()
        .unwrap_or_else(|e| panic!("invoke {ar}: {e}"));
    assert!(
        status.success(),
        "{ar} failed to build {}",
        archive.display()
    );
}
